<link rel="stylesheet" href="https://unpkg.com/gitalk/dist/gitalk.css">
<script type="text/javascript" src="https://unpkg.com/gitalk/dist/gitalk.min.js"></script>
<script type="text/javascript">
var gitalk = new Gitalk({
  clientID: 'f0fb045f5ae7d997ff8f',
  clientSecret: '83c6413086344a481582fdf4a68c8096e4dbc562',
  repo: 'Leo-Mu.github.io',
  owner: 'Leo-Mu',
  admin: ['Leo-Mu'],
})

gitalk.render('comments')
</script>
